### ISSUE TITLE
Publisher throws error for 'pin-canonicals' parameter when adding test cases

### ISSUE THREAD

**Issue by basharmsen** [HL7/fhir-ig-publisher#1117]
While using the FHIR IG Publisher (version 2.0.7), I encountered an error when attempting to add test cases to an Implementation Guide. The error message is:

`Unknown value for 'pin-canonicals' of 'profile-test-cases/profile-test-cases.json'`.

Upon investigating the source code, it seems that the issue arises from a `case` block in a `switch` statement which is not terminated with a `break` statement.

### Steps to Reproduce

1. Attempt to add test cases to an Implementation Guide using the value `profile-test-cases/profile-test-cases.json` for the `profile-test-cases` parameter.
2. Observe the error message during the generation of the IG.

### Expected Behavior

The test cases should be added successfully without any errors.

### Actual Behavior

An error message is thrown indicating an unknown value for `pin-canonicals`. The issue appears to be related to a `switch` statement in the source code of the publisher where a `case` block is not terminated with a `break` statement.

### Additional Context

The `case` block for `profile-test-cases` in the `switch` statement is not terminated with a `break` statement. Here is the relevant code snippet from [Publisher.java](https://github.com/HL7/fhir-ig-publisher/blob/f2fdf4e51a8d36a21aab47bb2932fd6e1cd4e9fb/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L3414):

```java
// ...
} else switch (pc) {
// ...
case "profile-test-cases":
    profileTestCases.add(p.getValue());
    // Missing break statement here
case "pin-canonicals":
// ...
```

It seems likely that this is the root cause of the problem, and addressing this should resolve the issue.

**Comment by lmckenzi** [comment]
Already fixed

**Comment by basharmsen** [comment]
Can you perphaps point me the commit where it has been fixed?

**Comment by patrick-werner** [comment]
I think this wasn't fixed yet:
https://github.com/HL7/fhir-ig-publisher/blob/6fb31bc7052aa5a7823c2604b19cf52fbc3424ac/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L3428
