### ISSUE TITLE
Validation fails for CDA instance against cda-core-2.0 IG

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#253]
I ran the following validation comment:

`java -jar validator_cli.jar C-CDA_R2-1_CCD.xml -version 4.0.1 -ig hl7.fhir.cda`

I received the following error:

```
Validating
  Validate 
C-CDA_R2-1_CCD.xml: Invalid date/time format: "2011-02-01T9"
Exception in thread "main" org.hl7.fhir.exceptions.FHIRException: ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "2011-02-01T9"
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:335)
        at org.hl7.fhir.validation.cli.services.ValidationService.validateSources(ValidationService.java:88)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:237)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:158)
Caused by: ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "2011-02-01T9"
        at org.hl7.fhir.r5.model.BaseDateTimeType.throwBadDateFormat(BaseDateTimeType.java:776)
        at org.hl7.fhir.r5.model.BaseDateTimeType.validateLengthIsAtLeast(BaseDateTimeType.java:839)
        at org.hl7.fhir.r5.model.BaseDateTimeType.parse(BaseDateTimeType.java:449)
        at org.hl7.fhir.r5.model.BaseDateTimeType.parse(BaseDateTimeType.java:51)
        at org.hl7.fhir.r5.model.PrimitiveType.fromStringValue(PrimitiveType.java:110)
        at org.hl7.fhir.r5.model.PrimitiveType.setValueAsString(PrimitiveType.java:166)
        at org.hl7.fhir.r5.model.BaseDateTimeType.setValueAsString(BaseDateTimeType.java:721)
        at org.hl7.fhir.r5.model.BaseDateTimeType.setValueAsV3String(BaseDateTimeType.java:763)
        at org.hl7.fhir.r5.model.DateTimeType.parseV3(DateTimeType.java:174)
        at org.hl7.fhir.r5.elementmodel.XmlParser.convertForDateFormatFromExternal(XmlParser.java:461)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:315)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parseChildren(XmlParser.java:377)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parse(XmlParser.java:199)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parse(XmlParser.java:183)
        at org.hl7.fhir.r5.elementmodel.XmlParser.parse(XmlParser.java:153)
        at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:550)
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:357)
        at org.hl7.fhir.validation.ValidationEngine.validate(ValidationEngine.java:327)
        ... 3 more
```

This appears to be a fundamental issue between the differences of FHIR and CDA, and how FHIR has a different date/time format compared to CDA.

Here is the CDA instance I validated against: [C-CDA_R2-1_CCD.zip](https://github.com/HL7/fhir-ig-publisher/files/6312783/C-CDA_R2-1_CCD.zip)

**Comment by grahamegrieve** [comment]
invalid date. Fixed in core validator. btw, raise validator issues against fhir core not the ig publisher

**Comment by ajagann1** [comment]
No longer see this error for valid cases of a date in the output of the validator when used on C-CDA_R2-1_CCD.xml.  There are other "Invalid date/time format" errors in the validation but valid ones are no longer flagged.

**Comment by seanmcilvenna** [comment]
Think we may still have a validation issue... but, at least the validator isn't throwing exceptions about it
