### ISSUE TITLE
Jurisdiction with ISO 3166:-2 codes cause publisher java.lang.NullPointerException

### ISSUE THREAD

**Issue by eborey** [HL7/fhir-ig-publisher#696]
Using ISO 3166:-2 codes for jurisdiction in profiles cause publisher to crash with java.lang.NullPointerException.
sushi v2.10.2
publisher.jar 1.3.12

For exemple the use of the following profile (fsh):
```
Profile: MyPatient
Parent: Patient
Description: "An example profile of the Patient resource."
* ^jurisdiction = urn:iso:std:iso:3166:-2#CA-QC
* name 1..* MS
```
will cause :
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.stateNameForCode" is null
	at org.hl7.fhir.igtools.publisher.Publisher.displayForStateCode(Publisher.java:8311)
	at org.hl7.fhir.igtools.publisher.Publisher.populateResourceEntry(Publisher.java:8189)
	at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:7980)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:6843)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1116)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:929)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:11384)
```

To reproduce, simply create a brand new IG :
sushi -i
add new attribute "jurisdiction" into input/fsh/patient.fsh (see files [patient.txt](https://github.com/HL7/fhir-ig-publisher/files/11557943/patient.txt))
./_updatePublisher.sh
./_genonce.sh
raise error on Generating Summary Outputs (see log [publisher.log](https://github.com/HL7/fhir-ig-publisher/files/11557904/publisher.log))

**Comment by lmckenzi** [comment]
I believe this is now addressed?

**Comment by grahamegrieve** [comment]
well, it's not happening, but the code remains fragile and a better error than an NPE would be appropriate

**Comment by eborey** [comment]
I still have the same error with FHIR IG Publisher Version 1.3.28 (I am on macOS 13.4.1 Ventura).

**Comment by eborey** [comment]
Just to let you know that this error is no longer raised (publisher 1.7.1).
