### ISSUE TITLE
Formal instance end up in the Examples folder of package

### ISSUE THREAD

**Issue by LodewijkSioen** [HL7/fhir-ig-publisher#861]
See: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Formal.20Instance.20ends.20up.20in.20the.20examples.20folder.20of.20package

The presence of a `meta.profile` on an instance of a profile will trigger the publisher to put the json-file of that instance in the `examples` folder of a package. This behaviour is unwanted if you want to define for example a PlanDefinition that adheres to a profile. That instance is an integral part of the IG and not just an example.

Example fsh:
```
Profile: MyOrganization
Parent: Organization
Title: "Test Organizatoin"
Id: my-organization
Description: "Test where this ends up"
* name 1..1

Instance: TestMyOrganization
InstanceOf: MyOrganization
Description: "This one ends up in the examples folder"
Usage: #definition
* name = "Test My Org"

Instance: TestOrganization
InstanceOf: Organization
Description: "This one ends up in the root folder"
Usage: #definition
* name = "Test Org"
```

**Comment by LodewijkSioen** [comment]
I have a repo here: https://github.com/LodewijkSioen/Fhsing-Expedition/blob/main/input/fsh/ExampleInWrongFolder.fsh

**Comment by grahamegrieve** [comment]
In principle this seems reasonable to me, but it's a change to a pretty long-standing arrangement, and I'm not sure how to do due diligence on this one

**Comment by lmckenzi** [comment]
Having meta.profile should set the R5 definition.profile, but NOT set definition.isExample.  @grahamegrieve will investigate whether this is an interversion conversion problem.

**Comment by grahamegrieve** [comment]
Fixed next release

**Comment by LodewijkSioen** [comment]
Sadly there is still a problem: examples of a profiled resource now end up in the root folder and not in the examples folder:
```
Instance: TestMyOrganization-Example
InstanceOf: MyOrganization
Description: "This one should end up in the examples folder"
Usage: #example
* name = "Example My Organization"

Instance: TestOrganization-Example
InstanceOf: Organization
Description: "This one should end up in the examples folder"
Usage: #example
* name = "Example Organization"
````
The `TestMyOrganization-Example` example will end up in the root folder.

Sushi will generate
```
{
        "reference": {
          "reference": "Organization/TestMyOrganization-Example"
        },
        "name": "TestMyOrganization-Example",
        "description": "This one should end up in the examples folder",
        "exampleCanonical": "http://example.org/StructureDefinition/my-organization"
      },
```
and the IG Publisher 
```
{
      "extension" : [{
        "url" : "http://hl7.org/fhir/tools/StructureDefinition/resource-information",
        "valueString" : "Organization"
      }],
      "reference" : {
        "reference" : "Organization/TestMyOrganization-Example"
      },
      "name" : "TestMyOrganization-Example",
      "description" : "This one should end up in the examples folder",
      "exampleCanonical" : "http://example.org/StructureDefinition/my-organization"
    },
```

**Comment by grahamegrieve** [comment]
fixed next release
